### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6304: character maps to <undefined>

### ISSUE THREAD

**Issue by NoahDragon** [google/tangent#13]
While installing the package under windows 8.1 in Conda environment (python 3.5.3), ran the `pip install tangent`, got the following error:
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6304: character maps to <undefined>
```

Any help would appreciate.

**Comment by alexbw** [comment]
Just updated the pip version to include recent fixes for this problem. Try again?

**Comment by NoahDragon** [comment]
Works, thanks for the quick response.
