### ISSUE TITLE
Reverse mode for array function not yet implemented

### ISSUE THREAD

**Issue by jkitchin** [google/tangent#28]
This is a very common idiom in numpy programming. It seems like it would be good to implement it.

```
def f(x):
    x = np.array(x)
    return x**2

df = tangent.grad(f)
```

raises: ReverseNotImplementedError: Reverse mode for function "array" is not yet implemented.

**Comment by alexbw** [comment]
Good idea. Fixed in c8ff080. Btw, adding new gradients is pretty straight-forward, check out the diff: https://github.com/google/tangent/commit/c8ff0808d03521b3919ae5eaf960f805c83455ef.

We do have a lot of gradients still to add for NumPy, and hope to get to it over the next week or so.
