### ISSUE TITLE
KeyError on integer arrays in gradient

### ISSUE THREAD

**Issue by jkitchin** [google/tangent#32]
I am not sure if this is a bug.

This works fine with float arrays.

```
def f(x):
    "the trace of x"
    sum = 0
    for i in range(x.shape[0]):
        sum += x[i, i]
    return sum

df = tangent.grad(f)

print(df(np.eye(3)))
```

#+RESULTS:
:RESULTS:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

:END:

```
print(df(np.eye(3, dtype=np.int)))
```

however raises:

```

KeyErrorTraceback (most recent call last)
<ipython-input-44-8e31db1a0f3c> in <module>()
----> 1 print(df(np.eye(3, dtype=np.int)))

/tmp/tmpMwgrX9/tangent_41b5.py in dfdx(x, bsum)
     19     tangent.push(_stack, i2, '_929efdb9')
     20     bx = tangent.init_grad(x)
---> 21     bx_t = tangent.init_grad(x_t)
     22 
     23     # Beginning of backward pass

/usr/local/google/home/kitchin/.local/lib/python2.7/site-packages/tangent/utils.pyc in init_grad(obj, allow_lazy_initializer)
    370     return 0.0
    371 
--> 372   initializer, supports_lazy_initializer = grad_initializers[type(obj)]
    373   if supports_lazy_initializer:
    374     if isinstance(obj, ZeroGradient):

KeyError: <type 'numpy.int64'>
```

It is not obvious to me what the result should be since integers are discrete, but a better error message might be helpful if there is no derivative.

**Comment by mdanatg** [comment]
We can add support for int values.
The point about the result is valid; the result would consist of applying the usual differentiation rules to integer variables, so I believe one could view it as a very coarse approximation of the real case.

**Comment by alexbw** [comment]
@jkitchin We shouldn't technically be able to differentiate w.r.t. integer inputs (since operations on integers are stepwise-constant, e.g. have a derivative of 0 almost everywhere), but we should either "just go for it", or provide a more useful error message. We'll make a decision and push a fix.

**Comment by jkitchin** [comment]
That sounds good. I don't know what the best approach is. Right now, it works a little like TensorFlow, when you try to do something that in Python would result in automatic casting. On one hand, it makes you be explicit if you have to do the casting yourself. A more useful error message might be a good solution to start with, and see if it issues about it being inconvenient come up.
