### ISSUE TITLE
Can't import "make_vjp"

### ISSUE THREAD

**Issue by rshap91** [google/tangent#47]
I pip installed tangent and can't get it to import. I think this has to do with upgrading tensorflow to 1.4 though not sure.

Mac Os Sierra 10.12.6 
Python 3.6
Tensorflow 1.4.0

Running in Jupyter notebook (or ipython)

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-b7bc666cce03> in <module>()
----> 1 import tangent

/Users/rick.shapiro/anaconda/lib/python3.6/site-packages/tangent/__init__.py in <module>()
     18 import gast
     19 
---> 20 from tangent import annotate
     21 from tangent import ast as ast_
     22 from tangent import compile as compile_

/Users/rick.shapiro/anaconda/lib/python3.6/site-packages/tangent/annotate.py in <module>()
     27 from tangent import cfg
     28 from tangent import quoting
---> 29 from tangent import tracing
     30 from tangent import utils
     31 

/Users/rick.shapiro/anaconda/lib/python3.6/site-packages/tangent/tracing.py in <module>()
     14 """Utilities for tracing code, a useful fallback when ahead-of-time AD fails.
     15 """
---> 16 from tensorflow.python.eager.backprop import make_vjp
     17 
     18 

ImportError: cannot import name 'make_vjp'
```

**Comment by alexbw** [comment]
You got it. We require a nightly build of TF 1.5 currently, as the make_vjp
function was introduced there.

**Comment by rshap91** [comment]
Sorry - don't understand, what does this mean I should do to fix it? or am I waiting for an update?

**Comment by alexbw** [comment]
You should update TensorFlow to 1.5. `pip install tangent` should have done that for you, but I suppose that didn't take. Could you try `pip install tf-nightly>=1.5.0.dev20171026` ?

**Comment by rshap91** [comment]
`pip install --upgrade tangent` says all requirements satisfied.
`pip install tf-nightly>=1.5.0.dev20171026` produces no output... and still same error when trying to import

**Comment by mdanatg** [comment]
I wonder if ipython grabs the wrong dependency. If your env sees TF version 1.4.0, then the import will fail. If you try `import tangent` inside a python (regular python, not ipython) prompt, do you still see the error?

I'd also try `pip install --ignore-installed tf-nightly` to force a reinstall.

**Comment by rshap91** [comment]
force reinstall worked! Thank you

**Comment by alexbw** [comment]
Awesome! Please let us know if anything else is an issue, we'd be happy to
help.
