### ISSUE TITLE
extra edges in control flow graph after "return"

### ISSUE THREAD

**Issue by dbieber** [google/tangent#54]
Issue:
The control flow graph that tangent builds sometimes has extra edges following a "return" statement.

Example:
```
def fn3(self):  # arguments
    if 2 > 1:  # compare
      return 1  # return1
    return 2  # return2
```

The cfg produced by build_cfg has the following edges:
arguments->compare
compare->return1
compare->return2
return1->return2  # this is the extra edge.

**Comment by dbieber** [comment]
Also the edge from `break` statements in the cfg leads back to the loop start, rather than to the post loop code.

```
  def fn3(self):  # arguments
    for i in range(10):  # for
      if i == 3:  # compare
        break  # break
      else:  
        pass  # pass
    return 1  # return
```

The cfg produced by build_cfg has the following edges:
arguments -> for
for -> compare
for -> return
compare -> pass
compare -> break
break -> for  # I would expect break -> return, rather than break -> for
pass -> for

**Comment by alexbw** [comment]
Thanks for the report. @bartvm, any really obvious fix that comes to mind? Otherwise I'll look into it.

**Comment by bartvm** [comment]
Multiple returns have never been supported AFAIK, and we should update fence to throw an error when they appear. Updating the CFG analysis to support them might require a bit of work; haven't thought too much about it.

The second example is definitely a bug. I don't immediately see the cause; [this line](https://github.com/google/tangent/blob/master/tangent/cfg.py#L157) should make sure that `break` should point to `cfg.exit` (since it's called after `self.set_head(iter_)`).

**Comment by dbieber** [comment]
I'm working on an implementation that should handle arbitrary nesting of loop, try-finally, and function definition frames. It supports multiple returns (and handles breaks properly) (and tries to do the right thing in the face of exception handling). I'll share it with you internally, and maybe it will be useful for tangent (either as a whole, or just the `break` piece of it).

**Comment by bartvm** [comment]
Nice. Exceptions, break statements, and nested loops should all be part of Tangent's CFG analysis though. If they're not working, we should probably fix them (although it's not entirely clear what the CFG of a try-except block looks like, given that it can jump from one basic block to the other at any point).

Some of the other features (multiple return statements, function definitions), could be useful for Tangent on the long term, but they can't be used to generate gradients naively (the problem being that the adjoint has multiple entry points, or that the adjoint needs to write into the outer scope).
