### ISSUE TITLE
forward mode nonexistent?

### ISSUE THREAD

**Issue by mcordelia** [google/tangent#60]
Hi,

the following code produces the subsequent error:

`tangent_df = tangent.grad(fun, verbose = 1, mode='forward')`

```
Traceback (most recent call last):
  File "autoDiff.py", line 114, in <module>
    tangent_df = tangent.grad(fun, verbose = 1, mode='forward')
TypeError: grad() got an unexpected keyword argument 'mode'
```

python version: Python 3.6.4 :: Anaconda, Inc.
tangent version: tangent                   0.1.9                     <pip>
(installed this morning via anaconda terminal using pip)

I also tried directly copy-pasting from the tutorial here: https://github.com/google/tangent/blob/master/README.md#forward-mode

resulting code: `tangent_df = tangent.grad(fun, mode='forward')`

but I get the same error.

code runs if I leave the 'mode' modifier out, for example the following:

`tangent_df = tangent.grad(fun, verbose=1)`

executes correctly.

Thanks.

**Comment by alexbw** [comment]
Hey, try `tangent.autodiff(fun,mode='forward')`
We switched from `grad` to `autodiff` for forward mode because it's not technically taking gradients. I'll update the docs to reflect this, sorry!

**Comment by alexbw** [comment]
The extra wrinkle is if you use `tangent.autodiff`, you have to provide the seed derivative. So `tangent.grad(f)(x)` would become `tangent.autodiff(f,mode='reverse')(x,1.0)` for taking gradients. `tangent.grad` is now a convenience wrapper specifically for gradients. If you think there's a more natural API, please let us know!

**Comment by mcordelia** [comment]
Hi, thanks for your comments! This definitely makes more sense now. I agree with you that the wrapper for gradients is much nicer. This solved my problem.
