### ISSUE TITLE
TypeError: 'type' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by krey** [google/tangent#82]
These two functions are identical, but only one of them "compiles".

```python
def g(x):
    if x > 0:
        y = x+2
    else:
        y = 2
    return y

tangent.grad(g)

# works fine

def h(x):
    if x <= 0:
        y = 2
    else:
        y = x+2
    return y

tangent.grad(h)

> TypeError: 'type' object has no attribute '__getitem__'
```

**Comment by bartvm** [comment]
To explain why this happened: In the second function the gradient contains `if ...: pass; else: dx = dy` which Tangent optimizes by swapping the branches to `if not ...: dx = dy`, but there was a bug in creating the `not` condition. In the first example, the branches didn't have to be swapped so the bug didn't appear.
