### ISSUE TITLE
Has tangent being incorporated into Eager Exexution to provide features similar to the script mode of PyTorch 1.0

### ISSUE THREAD

**Issue by wangkuiyi** [google/tangent#85]
I ask because I noticed that PyTorch 1.0 announced its [script mode](https://pytorch.org/2018/05/02/road-to-1.0.html), which, according to the [source code](https://github.com/pytorch/pytorch/blob/96d3f968ebcbbcff5a7d3adf1ceb357e78ca672a/torch/jit/__init__.py#L600), extracts the AST of the forward pass defined as a Python function, like what tangent does.

The script mode generates a graph to be executed by the Caffe2 runtime, thus differs from tangent that generates Python code. Is it a reasonable idea to make tangent the script mode of Eager Execution?

**Comment by mdanatg** [comment]
Yes - [AutoGraph](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/autograph) is a project derived from Tangent that does exactly that!
