### ISSUE TITLE
Failing evaluating Hessian

### ISSUE THREAD

**Issue by wiso** [google/tangent#88]
I have some problem computing second derivatives, probably I am doing something wrong.

    def f(x):
      return 0.5 * np.sum(x ** 2)

    tangent.grad(f)(np.array([1., 20.]))

This works, and returns the input, as expected.
The Hessian of f is the indentity matrix, for each input, I want to get that. I am naively doing

    tangent.grad(tangent.grad(f))(np.array([1., 2.]))

I get:

```
AssertionError                            Traceback (most recent call last)
<ipython-input-67-6d04546e37cf> in <module>()
----> 1 tangent.grad(tangent.grad(f))(np.array([1., 2.]))

/tmp/tmpw3W8Ib/tangent_f128.py in ddfdxdx(x, b_return, bbx)
     19     assert tangent.shapes_match(bx, bbx
     20         ), 'Shape mismatch between return value (%s) and seed derivative (%s)' % (
---> 21         numpy.shape(bx), numpy.shape(bbx))
     22 
     23     # Grad of: bx = _bx

AssertionError: Shape mismatch between return value ((2,)) and seed derivative (())
```

**Comment by bartvm** [comment]
The `grad` function performs reverse mode automatic differentiation, which means that it technically calculates a vector-Jacobian product. So `grad(f)` is implicitly calculating `matmul(1, J(x)) = J_f(x)` where `J_f(x)` is the Jacobian of `f` (which is of size `1 x n`).

However, `grad(f)` is a function with 2 inputs and 2 outputs, so its Jacobian is `2 x 2`. When you call `grad(grad(f))`, it tries to do `matmul(1, J_df(x)) = matmul(1, H_f(x))` which doesn't work. The 1 here is the default vector ("seed derivative"), which needs to be a vector of size 2 for the calculation to make sense.

If you want to calculate the full Hessian, you can do so by using all the basis vectors as seed derivatives: 
```python
def hessian(f):
    vhp = tangent.grad(tangent.grad(f))
    def hf(x):
        H = []
        for i in range(x.size):
            v = np.eye(1, x.size, i)[0]
            H.append(vhp(x, 1, v))
        return np.array(H)
    return hf
```

**Comment by wiso** [comment]
Thank you very much, it works!

I am using tangent in likelihood minimization and the hessian is needed to compute the error on measurements, it would be very useful to have this feature from the package.

I have some troubles to apply your recipe for function of multiple parameters. I am intereseted in the hessian just for the first argument

```
def f(x, y):
    return 0.5 * np.sum(x ** 2 + y)
```

When calling the hessian function I get

```
TypeError: hf() takes exactly 1 argument (2 given)
```
I would get exactly the same result as before.

Maybe this works:

```
def hessian(f):
    vhp = tangent.grad(tangent.grad(f))
    def hf(x, *args):
        H = []
        for i in range(x.size):
            v = np.eye(1, x.size, i)[0]
            H.append(vhp(x, *args, b_return=1, bbmus=v))
        return np.array(H)
    return hf
```
